allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
difficulty=1
enable-command-block=false
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=0
generate-structures=true
generator-settings=
hardcore=false
level-name=world
level-seed=3876023864849680181
level-type=DEFAULT
max-build-height=256
max-players=2
max-tick-time=60000
max-world-size=29999984
motd=W1 Minecraft Challenge
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
resource-pack=
resource-pack-sha1=
server-ip=127.0.0.1
server-port=25566
snooper-enabled=false
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
view-distance=5
white-list=false
